export const FEEDBACK_SUBJECTS = [
  "Account Information",
  "Product Information",
  "Order Status",
  "Damaged/Defective",
  "Returns, Received Wrong Item",
  "Order Changes",
  "Address Changes",
  "Missing Items",
  "Website Issues",
  "Lost Package",
  "Complaint",
  "Compliment",
  "Unsubscribe",
  "Other",
];
